INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Talent Land', 'Expo Guadalajara', 'Technology and innovation', '2018-04-03');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Technovation Challenge', 'Guadalajara', 'Woman in Tech', '2018-03-08');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Posa Dev', 'Centraal Bosch', 'Tech comminity christmas event', '2018-12-11');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Python Day', 'Por definir', 'Python & Django', '2018-06-07');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Java Dev Day', 'Centraal Bosch', 'Java, Spring, Kotlin, Microprofile', '2018-04-29');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Tech Quiero', 'Centraal Bosch', 'Woman in Tech', '2018-10-12');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('Fuckup Nights', 'Hackers & Founders', 'Entrepreneurship', '2018-07-21');
INSERT INTO EVENT (NAME, VENUE, TOPIC, DAY) VALUES('j4Guanatos', 'Hackers garage', 'Java', '2018-12-12');

INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(1, 'Robots in society', 'Sophia the Robot', 'Humanoid capable of talking to humans fluently');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(1, 'Free Software', 'Richard Stallman', 'Give user freedom with free software');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(2, 'Empowering girls', 'Technovation CEO', 'Empowering girls through tech and innovation');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(2, 'Apps for real problems', 'Gabriela Technovation', 'Solving Real life problems with Android apps');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(3, 'How to become a GDE', 'Joél Humberto', 'Become a GDE in 3 simple (but hard) steps');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(3, 'Kotlin everything', 'Sier Violence', 'Fuck Java, Kotlin everything');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(4, 'Jython', 'Guido van Rossum', 'Running Python inside JVM');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(4, 'Automate with Python', 'Emmanel Python', 'Using python for automation');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(5, 'Security for Java Developers', 'Héctor Paredes', 'How to secure Java and Spring apps');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(5, 'jUnit 5', 'Fer j4G', 'Testing Java 8 code with jUnit 5');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(6, 'Empowering women', 'Tatiana Estevez', 'Teaching tech to women to empower them');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(6, 'Empowering women', 'Tatiana Estevez', 'Teaching tech to women to empower them');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(7, 'Finantial inclusion', 'Kueski CEO', 'How to provide finantial inclusion with tech');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(7, 'Fintech', 'Kueski CTO', 'Technology at finantial startups');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(8, 'Spring Everything', 'Carlos Salazar', 'How to build everything with Spring Boot');
INSERT INTO TALK (EVENT_ID, NAME, SPEAKER, RESUME) VALUES(8, 'Android patterns', 'José Ángel', 'Building better Android');
