CREATE TABLE EVENT (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64),
  VENUE VARCHAR(64),
  TOPIC VARCHAR(128),
  DAY DATE
);

CREATE TABLE TALK (  
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EVENT_ID BIGINT,
	NAME VARCHAR(64),
	SPEAKER VARCHAR(64),
	RESUME VARCHAR(128),
	FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID)
);

